name: Frontend TypeCheck

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    frontend-typecheck:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Check for frontend changes
              uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
              id: filter
              with:
                  filters: |
                      frontend:
                        - 'blog-client/**'
                        - '.github/workflows/frontend-typecheck.yml'

            - name: Setup Node.js
              if: steps.filter.outputs.frontend == 'true'
              uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: blog-client/package-lock.json

            - name: Install dependencies
              if: steps.filter.outputs.frontend == 'true'
              working-directory: blog-client
              run: npm ci

            - name: Run TypeScript type check
              if: steps.filter.outputs.frontend == 'true'
              working-directory: blog-client
              run: npm run typecheck
